version: '3'
services:
    ms:
        #image: ooclab/eva
        build: .
        tty: true
        environment:
            PYTHONIOENCODING: utf-8
            PYTHONPATH: /work
            NOSE_NOCAPTURE: 1
        #dns: 223.5.5.5
        ports:
            - "3000:3000"
        volumes:
            - "./src:/work"
        #entrypoint: python /work/server.py

    postgres:
        image: postgres
        environment:
            POSTGRES_DB: remotex
            POSTGRES_USER: remotex
            POSTGRES_PASSWORD: remotex
        volumes:
            - "/data/product/remotex/db:/var/lib/postgresql/data"

    elasticsearch:
        image: elasticsearch:5.4.0
        ports:
            - "9200:9200"
            - "9300:9300"
        #sysctl -w vm.max_map_count=262144
        environment:
            ES_JAVA_OPTS: "-Xms256m -Xmx256m"
        volumes:
            - "./elastic/plugins:/usr/share/elasticsearch/plugins"
            - "/data/product/remotex/elastic:/usr/share/elasticsearch/data"
